### ISSUE TITLE
No results after setting everything correctly

### ISSUE THREAD

**Issue by kamyd** [Rkiefe/FEMCE#1]
Hello and Good Day.
Thank you for sharing your work, I have been trying to run a simulation but it is not giving me any answer, here is what I do:
1. Set a container
2. Load the STL file
3. Set the scaling
4. Mesh the geometry using the default setting
5. Load all the properties of gadolinium
6. Set multithread
7. Run MCE
and a popup windows opens for a minute or two, then becomes white and CPU cores unload, nothing is shown in the MCE window. 
Can you please guide me to rectify this problem?

<img width="256" alt="Screenshot 2024-08-20 064553" src="https://github.com/user-attachments/assets/46ec01f3-0dae-4ed3-8c0c-961524935230">

**Comment by Rkiefe** [comment]
Hello,
I'll be glad to help. Can you please clarify what you mean by "set the
fraction"?

Let's see:
  - Once you have the STL loaded you should see it in the "model" panel.
Make sure that it is showing your model.
  - After meshing the model, make sure a red object is shown in the "mesh"
panel, inside a blue container.
  - After loading all your properties, make sure all of them are visible in
the properties panel. Each of the data sets must have been plotted,
otherwise it's likely an issue with the dataset. Which might just be either
a problem with the extension used, or the data set format itself. Are you
using the MFT folder provided in the hub?
  - In the beginning try running without multithreading. If the number of
elements is small ( < 20.000 ~ depends on the geometry) it could be helpful
to diagnose the single thread case first.

I hope this helps. If it doesn't, feel free to let me know.

Best regards,
R. Kiefe

**Comment by kamyd** [comment]
Hello and Good Day. 
Thank you for the response. 

1. I meant the scaling setting. ("Scale geometry by" which I tried by setting 1 and 0.001) 
2. Yes, my model loads successfully, and its mesh is shown in red. Also, I received a message that the mesh was successful with the number of elements, etc.
3. The properties load, I checked the graph and yes I am applying the set of properties that were provided. (basically, I only changed the geometry)
I have attached one screenshot from each step, as you can see in the last screenshot, the CPU is not under load anymore and there are no results in the window. 
(I also ran a simulation with Geometry set to cm and scaling set to 1 with the same results/no answer)
![Capture](https://github.com/user-attachments/assets/ef5427b3-d31e-4707-9eb8-28beb4b91063)
![Capture2](https://github.com/user-attachments/assets/5e4b0a22-3891-406b-92c4-53c81943f3ff)
![Capture3](https://github.com/user-attachments/assets/e6d46713-3e4a-4613-bbf4-3b2e9089f70d)
![Capture4](https://github.com/user-attachments/assets/03f1e424-bcfa-49ed-850b-aaa027bbd87d)

I believe the simulation is not running correctly because the CPU goes under 90-100% load for 30 seconds and the window turns white, after that around two minutes later the window becomes responsive again which I have attached a screenshot of.


With gratitude.

**Comment by Rkiefe** [comment]
Hello,

Ok you seem to be doing everything right! I noticed that the number of
elements is very large, almost half a million elements. And you seem to be
using the multithreaded option (understandably so).

That leads me to believe that this is a memory issue. For each thread,
femce will create a N by N matrix where N is the number of elements. So,
depending on the amount of ram your computer has, that might not be
possible and hence the issue.

I can implement a memory evaluation to the software to check if it ever
runs out of memory, and then provide in the text box a message. As soon as
I do that, I'll let you know!

My suggestion is in the meantime, mesh using a specific "max element size"
and "min element size" such that the mesh has less elements overall. Try to
be under 100k. You can use the default mesh element size that appears in
the text box as reference, increasing the max and min values.

Best regards,
R. Kiefe

PS: I'm very glad you are using the software! I'll try to make it as user
friendly as possible. Also, if you use the most current version of the
software you don't have to make a container, it makes one automatically for
your stl file.

**Comment by Rkiefe** [comment]
Hello again,
I did some tests, and the CPU percentage is misleading. Here you can see
that it is at 0.1%, but it is in fact running a simulation at the moment,
using 80k elements. I have 64 gb of ram.

I'll add a marker to the app to indicate the step at which the simulation
is at (it goes from 1 to at most 50, and this 50 can be changed in the
advanced settings), this way you will be able to monitor the simulation.

Also, sometimes the rendering of the final results takes a long time.
Meaning that the simulation is done, but the plotting is not. And the
results window might also take a while to update because your simulation
uses so many elements.

So, another suggestion: after the simulation finishes, wait a long while
(maybe 10-20  mins just to be sure), and then check if the visualization
panel is updated. The simulation I did just now with 80k elements did take
long to update.


[image: image.png]
Best regards,
R. Kiefe

**Comment by kamyd** [comment]
Hello and thank you very much for your response and for your work. 

- Yes, I also believe it to be memory, today I was testing it on another PC with a higher amount of memory and the simulation ran for longer but it still failed. If you could add that option it would be a time saver in many cases and would help in accelerating the problem-solving step.
- I am actually trying to mesh with different element sizes but it fails, so I am still trying.
- I believe you already ran a simulation on "refrigerant_example.STL" file, if possible, can you please tell me how much memory your system had? **you already answered.**
- Also, thank you for the heads-up, I should just mention that I am on the latest version and it is still giving this notification "Remember, you must first create a container! Operation is allowed, but only for visualization."

- Just saw your new post, yesterday I left the system on without touching it after the start of the simulation and the last screenshot is from that time. (maybe 13 Hrs) 
- I can leave it for longer if you think it is still working and will update you on the result.

With gratitude.

**Comment by Rkiefe** [comment]
Hi,

The simulation I did today was for that "refrigerant_example.stl", yes.
Here is the set up. Keep in mind that this is a bad mesh setup. You want
the most amount of elements in the refrigerant, not the container.
![image](https://github.com/user-attachments/assets/4a2dab65-4cb9-4f74-a403-de0a3258624b)

My specs: AMD Ryzen 7 1700X Eight-Core Processor 3.40 GHz; 64 gb ram

A tip for better mesh generation is to right click on the model, press Edge
Labels and On. Then go to the edge list and write the edges of your
refrigerant. Then establish a local refinement size. This way you can have
larger element sizes overall, but a local element size smaller near those
edges. This might be time consuming and unnecessary if you can nail down a
good mesh with just the max and min settings, but it is useful for this
types of situations where you have a lot of elements.
![image](https://github.com/user-attachments/assets/e536eded-f254-42a3-941e-4ecac44fe9bf)

Yes, the latest version still gives that old message... I did not remove
it, I forgot and haven't updated the github because I don't want that to be
the only update for a new version of the software. But don't worry, it's
just a leftover.

13 hours is more than plenty, if it didn't show up then it's probably not
going to. Best of luck and thank you for the feedback!

Best regards,
R. Kiefe

**Comment by Rkiefe** [comment]
Hello again,
I've added a feature that we discussed. Now, you can see the iteration of the simulation in real time, making it easier to check if it is plotting the results or still doing calculations (or crashed from lack of memory). I'm going to close the issue as it can be considered "solved".
Cheers!
